name: CI/CD pipeline

# on what actions should run this action
on:
  push:
    branches:
      - master

# what all actions you want to be taken when you run this action
jobs:
  build_and_push:
    name: Build & push docker images
    runs-on: ubuntu-latest

    steps:
      #STEP 1: CHECKOUT REPO CODE
      - name: Checkout repo code
        uses: actions/checkout@v3

      #STEP 2: PREPARE DOCKER ENVIRONMENT TO BUILD
      - name: Prepare docker build ENVIRONMENT
        uses: docker/setup-buildx-action@v3

      #STEP 3: LOGIN TO DOCKER HUB
      - name: Login to docker hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      #STEP 4: BUILD AND PUSH CLIENT DOCKER IMAGE
      - name: Build and push client IMAGE
        uses: docker/build-push-action@v5
        with:
          context: ./client
          file: ./client/Dockerfile
          push: true
          tags: amol234docker/frontend:latest

      #STEP 5: BUILD AND PUSH SERVER DOCKER IMAGE
      - name: Build and push server IMAGE
        uses: docker/build-push-action@v5
        with:
          context: ./server
          file: ./server/Dockerfile
          push: true
          tags: amol234docker/backend:latest

      #STEP 6: BUILD AND PUSH WORKER DOCKER IMAGE
      - name: Build and push worker docker images
        uses: docker/build-push-action@v5
        with:
          context: ./worker
          file: ./worker/Dockerfile
          push: true
          tags: amol234docker/worker:latest

      #STEP 7: BUILD AND PUSH NGINX DOCKER IMAGE
      - name: Build and push nginx docker IMAGE
        uses: docker/build-push-action@v5
        with:
          context: ./nginx
          file: ./nginx/Dockerfile
          push: true
          tags: amol234docker/nginx:latest
